[package]
name = "minifi-sys"
version = "0.1.0"
edition = "2021"
description = "Raw FFI bindings to the Apache NiFi MiNiFi C API"
license = "Apache-2.0"

[dependencies]

# This crate needs bindgen to run the build script
[build-dependencies]
bindgen = "0.69"
