[package]
name = "minifi-native-sys"
version = "0.1.0"
edition = "2024"
description = "Raw FFI bindings to the Apache MiNiFi Native C API"
license = "Apache-2.0"

[dependencies]

[build-dependencies]
bindgen = "0.72.0"
